#!/bin/bash 

#+------------------------------------------------------------------------------+
#                             Gerador de Senhas                                 |
#+------------------------------------------------------------------------------+
# Elaborador por: Nilson Vieira                                                 |
#+------------------------------------------------------------------------------+
_VER=1.0

_GEN=`gpg --gen-random --armor 0 9`
# zenity --info --title="Gerador de Senhas" --text=$_GEN
zenity --question --title="Gerador de Senhas" --text "\n$_GEN" --ok-label="Copiar" --cancel-label="Cancelar"
if [[ $? == 0 ]];then
    echo $_GEN | xclip -i -selection clipboard
fi

check_update (){
    _VA=`cat /usr/bin/pgen | grep _VER | cut -d'=' -f2`
}