#!/bin/bash 

#+------------------------------------------------------------------------------+
#                             Gerador de Senhas                                 |
#+------------------------------------------------------------------------------+
# Elaborador por: Nilson Vieira                                                 |
#+------------------------------------------------------------------------------+
_VER=4

check_update (){
    _VA=`cat /usr/bin/pgen | grep _VER | cut -d'=' -f2 | head -1`
    _VU=`curl https://raw.githubusercontent.com/nilsonvieira/PasswordGenerator/master/version`

    if [[ $_VA -lt $_VU ]]; then
        zenity --question --width=300  --title="Gerador de Senhas" --text "Existem Atualizações Disponíveis. Deseja instalar agora?" --ok-label="Sim" --cancel-label="Não, Depois."
        if [[ $? == 0 ]]; then
            (
            echo "10" ; sleep 1
            cd /tmp/
            echo "40" ; sleep 1
            wget https://raw.githubusercontent.com/nilsonvieira/PasswordGenerator/master/pgen
            echo "70" ; sleep 1
            sudo mv /tmp/pgen /usr/bin/
            echo "100" ; sleep 1
            ) |
            zenity --progress \
            --title="Update" \
            --text="Update Package Password Generator..." \
            --percentage=0\
            --auto-close
        fi
    fi   
}

_GEN=`gpg --gen-random --armor 0 9`
# zenity --info --title="Gerador de Senhas" --text=$_GEN
zenity --question --title="Gerador de Senhas" --text "\n$_GEN" --ok-label="Copiar" --cancel-label="Cancelar"
if [[ $? == 0 ]]; then
    echo $_GEN | xclip -i -selection clipboard
    check_update
else
    check_update
fi
